Make sure offset_table_offset is written as 8 bytes
It's a `usize` value, but the output format expects 8 bytes. That's fine
on 64-bit targets, but 32-bit targets were failing tests:

    ---- stream::binary_writer::tests::bplist_roundtrip stdout ----
    thread 'stream::binary_writer::tests::bplist_roundtrip' panicked at 'assertion failed: `(left == right)`
      left: `8`,
     right: `4`: destination and source slices have different lengths', src/libcore/slice/mod.rs:2217:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
    ---- stream::binary_writer::tests::nskeyedarchiver_roundtrip stdout ----
    thread 'stream::binary_writer::tests::nskeyedarchiver_roundtrip' panicked at 'assertion failed: `(left == right)`
      left: `8`,
     right: `4`: destination and source slices have different lengths', src/libcore/slice/mod.rs:2217:9
    ---- stream::binary_writer::tests::utf16_roundtrip stdout ----
    thread 'stream::binary_writer::tests::utf16_roundtrip' panicked at 'assertion failed: `(left == right)`
      left: `8`,
     right: `4`: destination and source slices have different lengths', src/libcore/slice/mod.rs:2217:9

Casting to `u64` makes sure we have the correct size to write.